export const siteConfig = {
  name: "Siam Kabir",
  fullName: "MD. Siam Kabir",
  title: "Siam Kabir — Full-Stack Developer",
  description:
    "Siam Kabir is a full-stack web developer from Rangpur, Bangladesh specializing in Next.js, Laravel, and Supabase. Hire for business websites, crypto products, Telegram mini apps, and high-performance web apps.",
  url: process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://siam-kabir.com",
  locale: "en_US",
  email: "mdsiamkabir1@gmail.com",
  location: "Rangpur, Bangladesh",
  jobTitle: "Full-Stack Developer",
  keywords: [
    "Siam Kabir",
    "MD Siam Kabir",
    "full-stack developer",
    "Next.js developer",
    "Laravel developer",
    "Supabase developer",
    "web developer Bangladesh",
    "freelance web developer",
    "portfolio website developer",
    "crypto website developer",
    "Telegram mini app developer",
    "Rangpur developer",
    "KUET",
  ],
  socials: {
    github: "https://github.com/Siam-Kabir-2",
    linkedin: "https://www.linkedin.com/in/siam-kabir-1517b42b2/",
    fiverr: "https://www.fiverr.com/siam_kk",
    twitter: "https://x.com/_Siam__",
    instagram: "https://www.instagram.com/__the.lost.oni_/",
    telegram: "https://t.me/kurosaki106",
  },
} as const;
